### ISSUE TITLE
so many printf logs

### ISSUE THREAD

**Issue by JohnWins** [apriorit/mhook#16]
Hi, This is a nice hook library, but also there's so many "junk" information in code.
Such as, https://github.com/apriorit/mhook/blob/43c49493669bbcaee7744cbaf3628801ebba57f4/disasm-lib/disasm_x86.c#L86

after build in Release, there's so many log out there, not pretty, Why not use NDEBUG Micro to disable in release?
And also, assert function.

**Comment by SergiusTheBest** [comment]
Thank you for reporting, @JohnWins! Now it should be ok. Please check the latest version from master.
