### ISSUE TITLE
How to work with it?

### ISSUE THREAD

**Issue by 0xRapid** [apriorit/mhook#18]
Hiya, I used mhook(2.4) today, and it worked fine but the dll I created kept getting unloaded.

Now I found your project and I'm trying to figure out how to get started with it, the getting started is pretty small and I cant understand, if I use it with AppInit hooking method and I dont get how is it suppose to load the dll hooks if there is no dll entrypoint in your example test.

Can I have an explanation? do you guys have an irc/discord channel by any chance?

**Comment by SergiusTheBest** [comment]
Please, read this https://www.codeproject.com/Articles/49319/Easy-way-to-set-up-global-API-hooks article.  Mhook is responsible for intercepting API calls, but how to inject a DLL is up to you (as there are several methods for that with their own pros and cons).

**Comment by 0xRapid** [comment]
I'm just annoyed because it's c++ haha. I guess ill take a deeper look into it today. I used the one you provided already, problem is unloads the dll after the process is loaded. Any recommendation on how to debug the cause?

**Comment by SergiusTheBest** [comment]
How do you load the dll?

**Comment by 0xRapid** [comment]
What I do is I use APPINIT_dlls, same way from the link you sent above.

**Comment by SergiusTheBest** [comment]
Use debugger, probably you return FALSE from the DllMain or throw exception, or anything else.

**Comment by 0xRapid** [comment]
hookCtx[idx].pSystemFunction = SkipJumps((PBYTE)hookCtx[idx].pSystemFunction);

keeps making it crash. :(

Mhook_SetHook: Started on the job: 8B55FF8B / 0F87B0AA 
and then nothing...
 Exception thrown at 0x0F5CA8F7 (CyHook.dll) in CyHookTester.exe: 0xC0000005: Access violation reading location 0x8B55FF8B. occurred

Any clue what should I check?

**Comment by SergiusTheBest** [comment]
Could you post more of your code?
