### ISSUE TITLE
Supporting arm64 architecture

### ISSUE THREAD

**Issue by leochou0729** [apriorit/mhook#24]
Hello,
I just found this article on the web.
https://www.linux.com/training-tutorials/splice-hooking-unix-systems/
Seems that splice hooking supports the ARM architecture.
Would me mind sharing how to support ARM in the Mhook library? 
I have a Kylin OS running on ARM64 CPU, which has ftrace disabled, so I cannot use the ftrace hooking method described on Apriorit website. Thanks!

**Comment by SergiusTheBest** [comment]
Hi @leochou0729 ,

Actually it's not just a question of supporting amr64 but Linux/Unix too. Because currently mhook is a windows-only solution.
