### ISSUE TITLE
Potential access NULL pointer in mhook.c

### ISSUE THREAD

**Issue by pvthuyet** [apriorit/mhook#26]
Below function in mhook.c
```
static BOOL GetCurrentProcessSnapshot(PVOID* snapshot, PSYSTEM_PROCESS_INFORMATION* procInfo)
{
    // get a view of the threads in the system

    if (!CreateProcessSnapshot(snapshot))
    {
        ODPRINTF((L"mhooks: can't get process snapshot!"));
        return FALSE;
    }

    DWORD pid = GetCurrentProcessId();

    *procInfo = FindProcess(*snapshot, pid);
    return TRUE;
}
```
In case of FindProcess return NULL but this function is still return TRUE.
  
Solution: 
```
...
return NULL != *procInfo
```

**Comment by SergiusTheBest** [comment]
Hi @pvthuyet ,

You're right. However this situation will never happen as a current process id is always present in a processes snapshot. Also the solution requires `CloseProcessSnapshot`.

I think it's better to add a comment there instead of writing a code to handle the impossible situation.

BTW, did you find this manually or with some automatic tool?

**Comment by pvthuyet** [comment]
Hi @SergiusTheBest ,
> BTW, did you find this manually or with some automatic tool?

I met this problem with my project. Some how can't get the process info from snapshot, then access the NULL pointer.

> Also the solution requires CloseProcessSnapshot

I got your point.

**Comment by SergiusTheBest** [comment]
Are you able to reproduce this issue?

**Comment by pvthuyet** [comment]
Hi @SergiusTheBest ,
Now i know the root cause. 
I hooked ZwQuerySystemInformation and modified the result. 
That why can't find the process from snapshot. 
Therefore, we should check the NULL pointer too.

**Comment by SergiusTheBest** [comment]
Oh, so that's you messed up with WinAPI. Without the check you'll know that something is wrong much faster!

**Comment by pvthuyet** [comment]
thank you @SergiusTheBest

**Comment by pvthuyet** [comment]
@SergiusTheBest ,
But how about this fix to void crash if someone messed up as mine
```
...
	if (NULL == *procInfo) {
		CloseProcessSnapshot(*snapshot);
		return FALSE;
	}

	return TRUE;
```

**Comment by SergiusTheBest** [comment]
A crash is a better indication that something is really wrong.
