### ISSUE TITLE
Hooking at one specific address and calling the original function causes a crash.

### ISSUE THREAD

**Issue by kmramn** [apriorit/mhook#27]
The original function before hook at one address is like this

 
![image](https://user-images.githubusercontent.com/6291476/156581621-d6a4ab80-09fc-4349-a225-09f7fc49269f.png)

I am hooking at one specific memory address as shown in the image below

 
![image](https://user-images.githubusercontent.com/6291476/156581663-e05e7c2b-107b-48c0-9531-feef81fbd30a.png)

 
The hooked function successfully hooking function gets called, but while trying call back hooking function (System/Original function) it crashes. I tried to hook at different location address it works. The different address location where I successfully hooked and successfully called hooking function (System/Original function), as shown in the below images.

Before hook.
 
![image](https://user-images.githubusercontent.com/6291476/156581711-44248c39-a57a-4365-9e9c-e2dab0847089.png)

After hook.

 
![image](https://user-images.githubusercontent.com/6291476/156581744-772cc5a2-78f2-4ef6-9eee-8f71036406ac.png)

The code for hooked function and calling the hook function is as follows.

 
![image](https://user-images.githubusercontent.com/6291476/156581781-b18085a6-1082-4522-88c1-91648f809e56.png)

Your help is much appreciated. Please help me if I am making any mistake.

**Comment by SergiusTheBest** [comment]
Hi @kmramn !

At the moment we're unable to help due to Russian invasion of Ukraine. However could you trace code execution of `HookingFunction`? Does it jump to the original code?

**Comment by kmramn** [comment]
Hi @SergiusTheBest,

Everything will become alright. Thank you for your reply.

The above crash issue which is mentioned is also resolved by increasing the number of parameters as shown in the image below.

![image](https://user-images.githubusercontent.com/6291476/157398962-fe6052b9-3cbb-478f-a8ad-808f6ae0e1bb.png)

Earlier I have used only one parameter which was causing the crash. Since I am trying to hook at specific address instead of an API or function, I was exactly not sure how many number of parameter to input. After giving the correct or more number of parameters this issue is resolved.

Please take care of yourself. Thank you.
