### ISSUE TITLE
2 compiler errors when compiling with MingW on Windows and suggested fixes

### ISSUE THREAD

**Issue by chr0meice2** [apriorit/mhook#28]
Hello Team,

Just an FYI in order to get this to compile in mingw on Windows I had to make the following changes to mhook.c:

Line 262:

NTSTATUS(NTAPI PZwQuerySystemInformation)(
          SYSTEM_INFORMATION_CLASS SystemInformationClass,
       PVOID SystemInformation,
        ULONG SystemInformationLength,
     PULONG ReturnLength
    );

#define STATUS_INFO_LENGTH_MISMATCH      ((NTSTATUS)0xC0000004L)
//remove this.... static PZwQuerySystemInformation fnZwQuerySystemInformation = NULL;

//put this instead
static decltype(PZwQuerySystemInformation) *fnZwQuerySystemInformation=NULL;

Line 762:
        fnZwQuerySystemInformation = (decltype(PZwQuerySystemInformation)*)((void*)GetProcAddress(GetModuleHandle("ntdll.dll"), "ZwQuerySystemInformation"));

The error I was getting:

c:\mhook-master>g++  mhook-lib\mhook.c disasm-lib\disasm.c disasm-lib\disasm_x86.c  disasm-lib\cpu.c T:/hookdll/main.cpp  -o t:/hookdll/mhooktest.dll   -D_WIN32_WINNT=0x0502 -w -Wfatal-errors  -fpermissive -shared
mhook-lib\mhook.c:261:25: error: typedef 'PZwQuerySystemInformation' is initialized (use 'decltype' instead)
  261 | typedef NTSTATUS(NTAPI* PZwQuerySystemInformation)(

c:\mhook-master>g++  mhook-lib\mhook.c disasm-lib\disasm.c disasm-lib\disasm_x86.c  disasm-lib\cpu.c T:/hookdll/main.cpp  -o t:/hookdll/mhooktest.dll   -w -Wfatal-errors  -fpermissive -shared
mhook-lib\mhook.c: In function 'BOOL CreateProcessSnapshot(void**)':
mhook-lib\mhook.c:762:115: error: cannot convert 'const wchar_t*' to 'LPCSTR' {aka 'const char*'}
  762 |         fnZwQuerySystemInformation = (decltype(PZwQuerySystemInformation)*)((void*)GetProcAddress(GetModuleHandle(L"ntdll.dll")....

Compiler info:

c:\mhook-master>g++ --version
g++ (Rev10, Built by MSYS2 project) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Hope this helps

Best Regards,

-Avery T

**Comment by SergiusTheBest** [comment]
Hi @chr0meice2 ,

I've pushed the fix. Please, try it on your setup.

**Comment by SergiusTheBest** [comment]
I didn't use `decltype` as it raises C++ standard to 11.

**Comment by chr0meice2** [comment]
Thanks Sergey!! Confirming the fix works=) This is an awesome library
